version: "3.8"

services:
  admin:
    restart: unless-stopped
    build:
      context: ./
      args:
        - APP_PATH=packages/admin
    image: lit3d-system/admin
    networks:
      default:
    ports:
      - 443:443